- name: create a system user
  ansible.builtin.user:
    name: roboshop
    system: true
    shell: /sbin/nologin
    home: /app

- name: create a directory 
  ansible.builtin.file: 
    path: /app
    state: directory
