
- name: copying the service conifguration
  ansible.builtin.copy:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: start and enable service
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes

- name: configuring catalogue service
  ansible.builtin.systemd:
    name: catalogue
    daemon_reload: true
  tag:
    - name: conf-reload #only this part only running if we use tags
