- name:
    include_role:
      name: app-setup
- name:
  include_role: 
    name: nodejs

- name: copying the service conifguration
  ansible.builtin.copy:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: configuring catalogue service
  ansible.builtin.systemd:
    name: catalogue
    daemon_reload: true
  tag:
    - name: conf-reload


- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: we are using the registers
  ansible.builtin.debug:
  msg: {{ ls -ltr }}
  rgister: output




