- name: "Testing"
  hosts: ansible-node
  tasks:
    - name: "nginx installation"
      ansible.builtin.package:
        name: nginx
        state: present



# - name: nginx
#   hosts: local/anyserver
#   connection: local
#   become: yes
#   tasks:
#     - name: "nginx installation"
#       ansible.builtin.package:
#        - name: nginx
#        - state: present
