- name: "Testing"
  hosts: localhost
  connection: local
  become: yes
  #global or play level variable
  vars:
    user: "vicky"
  vars_files:
    - vars.yaml
  vars_prompt:
    - name: user
      prompt: "please enter username"
      private: true
  tasks:
    - name: installation nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: shows varaibles
      # local or task level variable
      vars:
        user: "vicky"
      ansible.builtin.debug:
        msg: "user name: {{ user }}"