- name: Testing 
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: "nginx installation"
      ansible.builtin.debug:
        msg: "nginx is installling....! boss"
        name : nginx
        state: present


