# - name: "Testing"
#   hosts: localhost
#   connection: local
#   become: yes
#   #global or play level variable
#   vars:
#     user: "vicky"
#   vars_files:
#     - vars.yaml
#   vars_prompt:
#     - name: user
#       prompt: "please enter username"
#       private: true
#   tasks:
#     - name: installation nginx
#       ansible.builtin.package:
#         name: nginx
#         state: present
#     - name: shows varaibles
#       # local or task level variable
#       vars:
#         user: "vicky"
#       ansible.builtin.debug:
#         msg: "user name: {{ user }}"



# - name: checkin number either it is postive or negative
#   hosts: localhost
#   connection: local
#   become: yes
#   vars_prompt:
#     - name: number
#       prompt: "please enter number"
#   tasks:
#     - name: show positive message
#       ansible.builtin.debug:
#         msg: "this is positive number"
#       when: (number | int) > 0
#     - name: show negative message
#       ansible.builtin.debug:
#         msg: "this is negative number"
#       when: (number | int) < 0



# - name: loops
#   hosts: localhost
#   connection: local
#   become: yes
#   tasks:
#   - name: instakling the packages
#     ansible.builtin.package:
#       name: "{{ item.name }}"
#       state: {{item.state}}
#     loop:
#     - {name: nginx, state: present}
#     - {name: mysql, state: absent}


- name: Testing
  hosts: localhost
  connection: local
  tasks:
  # -name: using ansible tags
  -name: using command module
  -name: ysing shell module
