# - name: install all
#   hosts: local
#   connection: local
#   tasks:
#       ansible.builtin.package:
#         state: present
#         state: installed

# playbooks: it is like conating the some set of tasks to run in remote server it is yaml 
#adohc commands are like one tim exectuble for this you dont need to write mutiple times
# ansible installed in one server thenk it is ansbile server..we xan can control other servers here 
# invetory is file that hold will all inforomation about remote connection details
#command: ansible-playbook -i inventory.inv playbook.yml
#command: ansible all -i -e ansible_user=ec2-user ansible_password=DevOps321

- name: installing all
  hosts: frontend # connecting to others 
  tasks:
  - name: nginx
    ansible.builtin.package:
      - name: nginx
        state: present
        enabled: yes

- name: installing roboshop
  hosts: local # connecting to local
  connection: local
  tasks: 
    - name: nginx installing and enabling 
      ansible.builtin.package:
        name: nginx
        state: present
    - name: nginx enabling nginx status
      ansible.builtin.package:
        name: nginx
        state: enable
    


